trigger: none
variables:
  - name: isFullSignoff
    value: true
  - name:  orgsCount
    value:
      -1
      -2
      -3

parameters:
 - name: orgsCount
   type: object
   default: [1,2,3,4,5,6] #Todo: Better way to pass the required number orgs as a object??
 - name: isFullSignoff
   type: boolean
   default: true
 - name: TestSets
   type: object
   default: ['TestSet1','TestSet2','TestSet3','TestSet4','TestSet5','TestSet6']
 - name: StageSets
   type: object
   default: ['StageSet1','StageSet2','StageSet3','StageSet4','StageSet5','StageSet6']
stages:
 - stage: test
   displayName: test
   jobs:
   - job:
   pool:
       vmImage: ubuntu-latest
       steps:
       - task: PowerShell@2
         inputs:
           displayName: 'RunningStage1_job1_Task'
           targetType: 'inline'
           script: |
             Write-Host "hi test task"
 
 - ${{ each job in parameters.StageSets }}:

 - stage: TipPrgprovision_${{ job }}
    dependsOn: test
    displayName: "${{ job }} Deploy"
    jobs:
      - job: Stage1
        displayName: Stage1_job1_${{ job }}
    pool: 
        vmImage: ubuntu-latest
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              Write-Host "Hello World"